{% set name = "flake8-bugbear" %}
{% set version = "21.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dd5395378ffd3661c2c231ff8ec138915c2e94899d7e557716b5071ab69c7214

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - flake8 >=3.0
    - attrs >=19.2.0

test:
  commands:
    - flake8 --version | grep flake8-bugbear

about:
  home: https://github.com/PyCQA/flake8-bugbear
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A plugin for Flake8 finding likely bugs and design problems in your program.

  description: |
    A plugin for Flake8 finding likely bugs and design problems in your
    program. Contains warnings that don't belong in pyflakes and pycodestyle.
  dev_url: https://github.com/PyCQA/flake8-bugbear

extra:
  recipe-maintainers:
    - dopplershift
