travis:
  secure:
    BINSTAR_TOKEN: Ui5/v8h38IIammHgZ51a24jnX1aqHvtW6BkBURV6fANcvJbMwmtrvMjbOWD7nnlHFUXZzxJHIg/d/6O8iHujm6daz4lRfRHFBEj5F1bqo6ZstMBVHYGXjf6bzK8omQ96bjRe85JHJafItw1G2OAWupQquvW/l2yWKWWnuvV2JMKjuKbg3jaSlFhnsKygL1ESb10AmZUALwY6GFK1q3PLIOMXIgbCwT/ApRI/ULMOLlOzJHqM44Aks1V39igsdsyxL4eELtwf3H/l5Pkbe0TkKszpWRmMDKS+YC6DRZAu4HpFY4OfOLFBFNvmGx/FZjKFpodMQoaOkyY6eNEwSDiUZkyW4Sv0UuZ5k5jJye9Y8E+XeXEii57N0Jpritri72kdNt33LnutoYBPfSDLmwvBl7RJj1FdPRB8BS2sqc/7GzZ+2H9Ukt+CX1ljeiqgHu2GwTNxEjFkYQrUnR9KY2fZVFxSToLF2SzpGNzXJFcBhERbJs8Oc7go9dWSm4R7ePfqtn/TF9GB8NF5sbXZ3BvOziCWoVoLYibnxxyKA4yG/0jpRKdMvuBpsP6IWNhYT6Uj+/6Kn3Fc6T2/pnAIIZqQT3Qxw0EdVQvhqCYVjwJsZ/D7SAZRK1WsyLxSSANGRtEHHLWBH1zMKy/Obc6VNHQ+LPUBR5Qil7PIuNG/jG5n6fA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
